// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKjNHf-I5dnRUcPAmw3E8VyI51-n-HJr0',
    appId: '1:306464648352:web:6c6d456cdaa00f9dd82dc5',
    messagingSenderId: '306464648352',
    projectId: 'lv-caller',
    authDomain: 'lv-caller.firebaseapp.com',
    storageBucket: 'lv-caller.appspot.com',
    measurementId: 'G-9H3RTLQ50L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs5n6OoPZF_I-PYSRLtqZBZZr9RNpNdik',
    appId: '1:306464648352:android:b4d13191c9ee3adcd82dc5',
    messagingSenderId: '306464648352',
    projectId: 'lv-caller',
    storageBucket: 'lv-caller.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmjq1YNgUxPtMhjAsTqvxgN2R-LBGpMvo',
    appId: '1:306464648352:ios:487f4b49d9553814d82dc5',
    messagingSenderId: '306464648352',
    projectId: 'lv-caller',
    storageBucket: 'lv-caller.appspot.com',
    iosClientId: '306464648352-skb09ve6rcs13m7kl8ca4c3jhg6jvsjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.lvCaller',
  );
}
